export type GuideGroup = 'public' | 'student' | 'teacher' | 'admin'

export interface GuideEntry {
  slug: string
  group: GuideGroup
  title: { en: string; ar: string }
  route: string
  linkRoute?: string
  purpose: { en: string; ar: string }
  instructions: { en: string[]; ar: string[] }
  permissions: { en: string; ar: string }
  integrations: { en: string; ar: string }
  connects: { en: string; ar: string }
}

const make = (
  slug: string,
  group: GuideGroup,
  title: [string, string],
  route: string,
  purpose: [string, string],
  instructions: [string[], string[]],
  permissions: [string, string],
  integrations: [string, string],
  connects: [string, string],
  linkRoute?: string,
): GuideEntry => ({
  slug, group, title: { en: title[0], ar: title[1] }, route,
  ...(linkRoute ? { linkRoute } : {}),
  purpose: { en: purpose[0], ar: purpose[1] },
  instructions: { en: instructions[0], ar: instructions[1] },
  permissions: { en: permissions[0], ar: permissions[1] },
  integrations: { en: integrations[0], ar: integrations[1] },
  connects: { en: connects[0], ar: connects[1] },
})

export const TIPS_REGISTRY: GuideEntry[] = [
  make('public-home', 'public', ['Home', 'الرئيسية'], '/', ['Introduce Be Fluent and direct visitors to the right entry point.', 'تعرّف بمنصة Be Fluent وتوجّه الزائر إلى مدخل مناسب.'], [['Review the learning approach and available paths.', 'Choose sign in or create an account to continue.'], ['تعرّف على منهج التعلّم والمسارات المتاحة.', 'اختر تسجيل الدخول أو إنشاء حساب للمتابعة.']], ['Public visitor; account actions require authentication.', 'متاحة للزائر؛ إجراءات الحساب تتطلب المصادقة.'], ['Authentication uses the configured NextAuth providers; do not assume a phone OTP provider.', 'تستخدم المصادقة مزودي NextAuth المضبوطين؛ لا تفترض وجود مزود OTP للهاتف.'], ['Entry point to account creation and the role-specific dashboard.', 'مدخل لإنشاء الحساب ولوحة التحكم المناسبة للدور.']),
  make('auth-login', 'public', ['Sign in', 'تسجيل الدخول'], '/auth/login', ['Authenticate an existing learner or team member.', 'مصادقة طالب أو عضو فريق لديه حساب.'], [['Enter the account credentials and submit.', 'Use the password recovery route if access is lost.'], ['أدخل بيانات الحساب وأرسلها.', 'استخدم مسار استعادة كلمة المرور عند فقدان الوصول.']], ['Unauthenticated visitors; successful access follows assigned role permissions.', 'للزوار غير المسجلين؛ ويتبع الوصول بعد النجاح صلاحيات الدور.'], ['NextAuth session and configured credential/provider setup; delivery channels depend on deployment configuration.', 'جلسة NextAuth وإعداد بيانات الاعتماد أو المزود؛ قنوات الإرسال تعتمد على إعداد النشر.'], ['Returns the user to the role-appropriate dashboard after authentication.', 'يعيد المستخدم بعد المصادقة إلى لوحة الدور المناسبة.']),
  make('auth-register', 'public', ['Create account', 'إنشاء حساب'], '/auth/register', ['Create an account for a new learner.', 'إنشاء حساب لمتعلم جديد.'], [['Complete the requested identity fields.', 'Review the resulting account and continue to the student space.'], ['أكمل حقول الهوية المطلوبة.', 'راجع الحساب الناتج وانتقل إلى مساحة الطالب.']], ['Public registration; administrative provisioning and approval rules may apply.', 'التسجيل متاح للزوار؛ وقد تنطبق قواعد الإدارة والموافقة.'], ['Account persistence and verification depend on enabled auth and mail configuration.', 'حفظ الحساب والتحقق منه يعتمدان على إعداد المصادقة والبريد.'], ['Feeds the learner profile, onboarding level and goals, then student learning.', 'يرتبط بملف المتعلم وتحديد المستوى والأهداف ثم تعلم الطالب.']),
  make('auth-forgot-password', 'public', ['Password recovery', 'استعادة كلمة المرور'], '/auth/forgot-password', ['Start the configured password reset process.', 'بدء عملية إعادة تعيين كلمة المرور المضبوطة.'], [['Submit the account email requested by the screen.', 'Follow the recovery message if mail delivery is enabled.'], ['أرسل البريد المطلوب في الشاشة.', 'اتبع رسالة الاستعادة إذا كان إرسال البريد مفعّلًا.']], ['Public route; only the account owner should complete the reset.', 'مسار عام؛ يجب أن يكمل إعادة التعيين صاحب الحساب فقط.'], ['Requires the deployed reset-token and email delivery path; availability is configuration-dependent.', 'يتطلب مسار رمز إعادة التعيين والبريد في بيئة النشر؛ التوفر يعتمد على الإعداد.'], ['Restores sign-in access, then returns to the role-specific workspace.', 'يعيد الوصول لتسجيل الدخول ثم مساحة العمل حسب الدور.']),
  make('dashboard-router', 'public', ['Role dashboard redirect', 'توجيه لوحة الدور'], '/dashboard', ['Route an authenticated user to the workspace associated with their role.', 'توجيه المستخدم المسجل إلى مساحة العمل المناسبة لدوره.'], [['Sign in first, then open the dashboard route.', 'If access is incorrect, ask an administrator to verify the assigned role.'], ['سجل الدخول أولًا ثم افتح مسار لوحة التحكم.', 'إذا كان الوصول غير صحيح، اطلب من الإدارة التحقق من الدور.']], ['Authenticated user; destination authorization remains independently enforced.', 'للمستخدم المسجل؛ ويظل تصريح الوجهة مطبقًا بصورة مستقلة.'], ['NextAuth session and the role-routing logic in the application.', 'جلسة NextAuth ومنطق توجيه الأدوار في التطبيق.'], ['Entry point that routes student, teacher and administration roles to their own workspaces.', 'مدخل يوجّه الطالب والمدرس والإدارة إلى مساحات عملهم.']),

  make('student-home', 'student', ['Student dashboard', 'لوحة الطالب'], '/dashboard/student', ['Give the learner a daily summary of goals, level, classes and next actions.', 'تمنح المتعلم ملخصًا يوميًا للمستوى والأهداف والحصص والخطوات التالية.'], [['Check the next scheduled class and outstanding homework.', 'Open recent teacher feedback and keep the monthly goal in view.'], ['راجع الحصة القادمة والواجبات المطلوبة.', 'افتح ملاحظات المدرس الأخيرة وتابع الهدف الشهري.']], ['Authenticated STUDENT; data is scoped to the learner account.', 'للطالب المسجل؛ البيانات مرتبطة بحسابه.'], ['Reads platform class, learning and assignment records; QMeet is only available when provisioned.', 'تعرض سجلات الحصص والتعلّم والواجبات؛ QMeet متاح فقط عند تهيئته.'], ['Overview for level/goals → class → feedback → homework → progress.', 'ملخص لمسار المستوى والأهداف ← الحصة ← الملاحظات ← الواجب ← التقدم.']),
  make('student-learning', 'student', ['Learning', 'التعلّم'], '/dashboard/student/learning', ['Show learning content relevant to the student’s current level and goals.', 'عرض محتوى تعلّم مناسب لمستوى الطالب وأهدافه الحالية.'], [['Choose the learning area or focus shown in the page.', 'Use goal-oriented materials, then revisit progress.'], ['اختر مجال التعلم أو محور التركيز الظاهر.', 'استخدم مواد مرتبطة بالهدف ثم راجع التقدم.']], ['STUDENT; content and progress are account-scoped.', 'للطالب؛ المحتوى والتقدم مرتبطان بالحساب.'], ['Platform content and progress records; no external learning provider is assumed.', 'محتوى المنصة وسجلات التقدم؛ لا يُفترض مزود تعلم خارجي.'], ['Uses level and goals as inputs; practice and lesson activity feed progress.', 'يستخدم المستوى والأهداف مدخلات؛ وتغذي الممارسة والدروس التقدم.']),
  make('student-learning-goals', 'student', ['Goals view', 'عرض الأهداف'], '/dashboard/student/learning?view=Goals', ['Focus the learning area on goal planning and current targets.', 'تركيز مساحة التعلم على التخطيط والأهداف الحالية.'], [['Open Goals from the learning navigation or use the route link.', 'Review the general and monthly targets before choosing practice.'], ['افتح الأهداف من تنقل التعلّم أو استخدم الرابط.', 'راجع الهدف العام والشهري قبل اختيار التدريب.']], ['STUDENT; changes are limited to the learner’s own goals where editing is enabled.', 'للطالب؛ تقتصر التغييرات على أهدافه عند إتاحة التحرير.'], ['Goal persistence is platform-backed; no external goal service is assumed.', 'حفظ الأهداف داخل المنصة؛ لا يُفترض نظام خارجي للأهداف.'], ['Goals guide class focus, selected materials and progress review.', 'توجّه الأهداف تركيز الحصص والمواد ومراجعة التقدم.']),
  make('student-classes', 'student', ['My classes', 'حصصي'], '/dashboard/student/classes', ['Review upcoming and past classes and join when the session is available.', 'مراجعة الحصص القادمة والسابقة والانضمام عند إتاحة الجلسة.'], [['Check the class time, teacher and status.', 'Use the join action only when enabled for the scheduled session.'], ['راجع وقت الحصة والمدرس وحالتها.', 'استخدم الانضمام عند تفعيله للحصة المجدولة.']], ['STUDENT; only the learner’s own assigned classes.', 'للطالب؛ حصصه المعيّنة فقط.'], ['QMeet is a target integration; meeting creation, embedding and provider readiness must be confirmed in deployment.', 'QMeet تكامل مستهدف؛ يجب تأكيد إنشاء الاجتماع والتضمين وجاهزية المزود في النشر.'], ['A class produces attendance/session context for teacher feedback and homework.', 'توفر الحصة سياق الحضور والجلسة لملاحظات المدرس والواجب.']),
  make('student-feedback', 'student', ['Feedback', 'ملاحظات المدرس'], '/dashboard/student/feedback', ['Read teacher feedback published for the student.', 'قراءة ملاحظات المدرس المنشورة للطالب.'], [['Open a published class note.', 'Review strengths, improvement focus and any vocabulary or pronunciation examples.'], ['افتح ملاحظة حصة منشورة.', 'راجع نقاط القوة ومحور التحسين وأمثلة المفردات أو النطق.']], ['STUDENT; private teacher notes are not student-visible.', 'للطالب؛ ملاحظات المدرس الخاصة غير مرئية.'], ['Platform feedback records; WhatsApp notification is conditional on a separately configured integration and consent.', 'سجلات الملاحظات داخل المنصة؛ إشعار WhatsApp مشروط بتكامل وموافقة منفصلين.'], ['Published feedback informs homework and the next learning focus.', 'توجّه الملاحظات المنشورة الواجب ومحور التعلم التالي.']),
  make('student-homework', 'student', ['Homework', 'الواجبات'], '/dashboard/student/homework', ['Track assigned work, due dates, submissions and review status.', 'متابعة الواجبات والمواعيد والتسليمات وحالة المراجعة.'], [['Open an assignment and read the instructions and due date.', 'Submit using the response type supported by that assignment.', 'Return to check teacher review and completion.'], ['افتح الواجب واقرأ التعليمات والموعد.', 'أرسل الإجابة وفق نوع الواجب.', 'عد للتحقق من مراجعة المدرس والإكمال.']], ['STUDENT; assignments and submissions are scoped to the learner.', 'للطالب؛ الواجبات والتسليمات خاصة بحسابه.'], ['File upload and media handling depend on configured storage and supported submission types.', 'رفع الملفات والوسائط يعتمدان على التخزين المضبوط وأنواع التسليم المدعومة.'], ['Created from class or learner context; teacher review can generate feedback and progress signals.', 'ينشأ من سياق الحصة أو الطالب؛ وتنتج عن مراجعة المدرس ملاحظات ومؤشرات تقدم.']),
  make('student-profile', 'student', ['Profile', 'الملف الشخصي'], '/dashboard/student/profile', ['Review personal and learning identity details.', 'مراجعة بيانات الهوية والتعلم الشخصية.'], [['Check contact and profile details.', 'Confirm level and learning preferences with the teacher when needed.'], ['راجع بيانات الاتصال والملف.', 'أكد المستوى وتفضيلات التعلم مع المدرس عند الحاجة.']], ['STUDENT; only own profile. Some learning fields may be staff-managed.', 'للطالب؛ ملفه فقط. قد يدير الفريق بعض حقول التعلم.'], ['Platform account records; external identity sync is not assumed.', 'سجلات حساب المنصة؛ لا يُفترض مزامنة هوية خارجية.'], ['Profile identity is referenced by classes, goals, feedback and assignments.', 'ترتبط هوية الملف بالحصة والأهداف والملاحظات والواجبات.']),
  make('student-level-progress', 'student', ['Level progress', 'تقدم المستوى'], '/dashboard/student/level-progress', ['Help the learner understand current level and learning progress.', 'مساعدة المتعلم على فهم مستواه وتقدمه.'], [['Review the current level and indicators presented.', 'Use teacher feedback and completed work to choose the next focus.'], ['راجع المستوى الحالي والمؤشرات المعروضة.', 'استخدم ملاحظات المدرس والعمل المكتمل لاختيار التركيز التالي.']], ['STUDENT; own progress only.', 'للطالب؛ تقدمه فقط.'], ['Platform learning data; progress reflects available recorded activity, not an external certification.', 'بيانات التعلم داخل المنصة؛ يعكس التقدم النشاط المسجل ولا يمثل شهادة خارجية.'], ['Summarizes level, goals, classes, feedback and homework activity.', 'يلخص المستوى والأهداف والحصص والملاحظات والواجبات.']),
  make('student-lessons', 'student', ['Lessons library', 'مكتبة الدروس'], '/dashboard/student/lessons', ['Browse lesson material available to the learner.', 'استعراض مواد الدروس المتاحة للمتعلم.'], [['Browse lessons and open a lesson suited to the current level.', 'Complete the activity, then return to learning or progress.'], ['تصفح الدروس وافتح ما يناسب المستوى الحالي.', 'أكمل النشاط ثم عد إلى التعلّم أو التقدم.']], ['STUDENT; published and level-appropriate content only.', 'للطالب؛ المحتوى المنشور والملائم للمستوى فقط.'], ['Content may include platform-hosted or external links; each item’s provider is determined by its content.', 'قد يتضمن المحتوى مواد مستضافة أو روابط خارجية؛ يحدد العنصر مزوده.'], ['Lesson activity complements class work and level goals.', 'يكمل نشاط الدرس عمل الحصة وأهداف المستوى.']),
  make('student-lesson-detail', 'student', ['Lesson detail', 'تفاصيل الدرس'], '/dashboard/student/lessons/[id]', ['Present a selected lesson and its learning activity.', 'عرض درس محدد ونشاطه التعليمي.'], [['Open a lesson from the library; this route needs a real lesson ID.', 'Follow the lesson content and use the available completion action.'], ['افتح الدرس من المكتبة؛ يحتاج هذا المسار إلى معرّف درس فعلي.', 'اتبع محتوى الدرس واستخدم إجراء الإكمال المتاح.']], ['STUDENT; lesson access is subject to publication and level rules.', 'للطالب؛ يخضع الوصول للنشر وملاءمة المستوى.'], ['Provider depends on lesson media and configured storage; external content may require its own service.', 'يعتمد المزود على وسائط الدرس والتخزين؛ وقد يحتاج المحتوى الخارجي لخدمته.'], ['Selected from lessons and contributes to the learner’s study activity.', 'يُفتح من مكتبة الدروس ويسهم في نشاط تعلم الطالب.'], '/dashboard/student/lessons'),
  make('student-schedule-sessions', 'student', ['Schedule sessions', 'جدولة الجلسات'], '/dashboard/student/schedule-sessions', ['Show session scheduling options available to a learner.', 'عرض خيارات جدولة الجلسات المتاحة للمتعلم.'], [['Review available sessions and any eligibility notes.', 'Confirm a booking only when a slot and action are available.'], ['راجع الجلسات المتاحة وملاحظات الأهلية.', 'أكد الحجز عند توفر موعد وإجراء صالح.']], ['STUDENT; booking scope and availability are controlled by platform rules.', 'للطالب؛ تخضع الحجوزات لقواعد المنصة والتوفر.'], ['Calendar or booking-provider integration is not guaranteed; confirm operational configuration.', 'تكامل التقويم أو مزود الحجز غير مضمون؛ يلزم تأكيد الإعداد التشغيلي.'], ['A confirmed session appears in classes and can lead to attendance, feedback and homework.', 'تظهر الجلسة المؤكدة ضمن الحصص ويمكن أن تقود للحضور والملاحظات والواجب.']),
  make('student-speaking', 'student', ['Speaking rooms', 'غرف المحادثة'], '/dashboard/student/speaking', ['Access speaking practice spaces available to the student.', 'الوصول إلى مساحات ممارسة التحدث المتاحة للطالب.'], [['Choose an available speaking room.', 'Check participation guidance before entering.'], ['اختر غرفة محادثة متاحة.', 'راجع إرشادات المشاركة قبل الدخول.']], ['STUDENT; room availability and participation rules apply.', 'للطالب؛ تنطبق قواعد توفر الغرف والمشاركة.'], ['Real-time room service availability depends on deployment; do not assume QMeet powers community rooms.', 'يعتمد توفر الغرف الفورية على النشر؛ لا يُفترض أن QMeet يشغل غرف المجتمع.'], ['Speaking practice supports goals and can inform teacher follow-up.', 'تدعم ممارسة التحدث الأهداف وقد تفيد متابعة المدرس.']),
  make('student-speaking-room', 'student', ['Speaking room detail', 'تفاصيل غرفة المحادثة'], '/dashboard/student/speaking/[roomId]', ['Open a specific speaking room.', 'فتح غرفة محادثة محددة.'], [['Open a room from the speaking list using its actual room ID.', 'Follow room instructions and leave when finished.'], ['افتح الغرفة من القائمة باستخدام معرّفها الفعلي.', 'اتبع إرشادات الغرفة وغادر عند الانتهاء.']], ['STUDENT; room membership and access rules apply.', 'للطالب؛ تنطبق قواعد العضوية والوصول.'], ['Live media depends on the configured room service and browser permissions.', 'يعتمد البث المباشر على خدمة الغرف المضبوطة وأذونات المتصفح.'], ['Room practice sits alongside classes and self-directed learning.', 'تقع ممارسة الغرفة إلى جانب الحصص والتعلم الذاتي.'], '/dashboard/student/speaking'),
  make('student-achievements', 'student', ['Achievements', 'الإنجازات'], '/dashboard/student/achievements', ['Reflect recorded learner milestones and completed activities.', 'عرض إنجازات المتعلم المسجلة والأنشطة المكتملة.'], [['Review earned achievements and their criteria where shown.', 'Use them as reflection, not as a substitute for teacher progress review.'], ['راجع الإنجازات ومعاييرها عند ظهورها.', 'استخدمها للتأمل لا بدلًا من مراجعة تقدم المدرس.']], ['STUDENT; own achievements only.', 'للطالب؛ إنجازاته فقط.'], ['Uses platform activity records; no external credentialing service is implied.', 'يعتمد على سجلات نشاط المنصة؛ ولا يعني وجود جهة اعتماد خارجية.'], ['Recognizes activity across learning, homework and progress.', 'يوثق النشاط عبر التعلم والواجبات والتقدم.']),
  make('student-leaderboard', 'student', ['Leaderboard', 'لوحة الترتيب'], '/dashboard/student/leaderboard', ['Show leaderboard information where the feature is enabled.', 'عرض معلومات ترتيب المتعلمين عند تفعيل الميزة.'], [['Review the displayed ranking and its context.', 'Do not treat ranking as a CEFR level or formal assessment.'], ['راجع الترتيب المعروض وسياقه.', 'لا تعتبر الترتيب مستوى CEFR أو تقييمًا رسميًا.']], ['STUDENT; visibility depends on platform configuration and privacy rules.', 'للطالب؛ يخضع العرض لإعداد المنصة والخصوصية.'], ['Platform activity aggregation; external ranking service is not assumed.', 'تجميع نشاط المنصة؛ لا يُفترض مزود ترتيب خارجي.'], ['Separate motivational view; authoritative progress is in level and teacher records.', 'عرض تحفيزي مستقل؛ التقدم المرجعي في المستوى وسجلات المدرس.']),
  make('student-cart', 'student', ['Cart', 'السلة'], '/dashboard/student/cart', ['Review items selected for purchase before checkout.', 'مراجعة العناصر المختارة قبل إتمام الشراء.'], [['Check package details and totals.', 'Proceed to checkout only when the summary is correct.'], ['راجع تفاصيل الباقة والإجمالي.', 'انتقل للدفع بعد التأكد من صحة الملخص.']], ['Authenticated learner or visitor as checkout policy permits.', 'للمتعلم المسجل أو الزائر حسب سياسة الدفع.'], ['Payment gateway and transaction completion depend on configured provider; do not assume a live payment connection.', 'يعتمد الدفع وإتمام المعاملة على المزود المضبوط؛ لا يُفترض اتصال دفع فعّال.'], ['Connects package discovery to checkout and order history.', 'يربط اكتشاف الباقات بالدفع وسجل الطلبات.']),
  make('student-checkout', 'student', ['Checkout', 'إتمام الشراء'], '/dashboard/student/checkout', ['Confirm a selected purchase and its payment path.', 'تأكيد عملية الشراء ومسار الدفع.'], [['Verify the selected package and final amount.', 'Complete payment only through the configured secure provider.'], ['تحقق من الباقة والمبلغ النهائي.', 'أكمل الدفع عبر المزود الآمن المضبوط فقط.']], ['Requires the account and purchase permissions specified by the checkout.', 'يتطلب الحساب وصلاحيات الشراء المحددة في صفحة الدفع.'], ['Payment processing is provider-dependent and must be confirmed before production use.', 'معالجة الدفع تعتمد على المزود ويجب تأكيدها قبل الاستخدام الإنتاجي.'], ['Successful orders appear in order history and may affect subscription access.', 'تظهر الطلبات الناجحة في سجل الطلبات وقد تؤثر في صلاحية الاشتراك.']),
  make('student-my-orders', 'student', ['My orders', 'طلباتي'], '/dashboard/student/my-orders', ['Review order records associated with the learner.', 'مراجعة الطلبات المرتبطة بالمتعلم.'], [['Open an order to inspect its status and details.', 'Contact the configured support route if a payment status needs review.'], ['افتح الطلب لمراجعة حالته وتفاصيله.', 'تواصل عبر مسار الدعم المضبوط عند الحاجة لمراجعة الدفع.']], ['STUDENT; own order history only.', 'للطالب؛ سجل طلباته فقط.'], ['Payment status is sourced from platform records and any configured gateway reconciliation.', 'تأتي حالة الدفع من سجلات المنصة وتسوية بوابة الدفع إن كانت مضبوطة.'], ['Follows cart and checkout; subscription access is managed separately.', 'يتبع السلة والدفع؛ وتدار صلاحية الاشتراك وفق مسارها.']),
  make('student-vocabulary', 'student', ['Vocabulary', 'المفردات'], '/dashboard/student/vocabulary', ['Provide vocabulary study areas connected to learning.', 'توفير مساحات لدراسة المفردات المرتبطة بالتعلّم.'], [['Choose a vocabulary activity.', 'Review expressions from lessons or teacher feedback.'], ['اختر نشاطًا للمفردات.', 'راجع التعبيرات من الدروس أو ملاحظات المدرس.']], ['STUDENT; learning content is account and level scoped.', 'للطالب؛ المحتوى مرتبط بالحساب والمستوى.'], ['Platform vocabulary content; no external dictionary provider is implied.', 'محتوى مفردات المنصة؛ لا يُفترض قاموس خارجي.'], ['Vocabulary practice reinforces class feedback and learning goals.', 'يعزز تدريب المفردات ملاحظات الحصة وأهداف التعلم.']),
  make('student-vocabulary-daily', 'student', ['Daily vocabulary', 'مفردات اليوم'], '/dashboard/student/vocabulary/daily', ['Offer a focused daily vocabulary study session.', 'تقديم جلسة مركزة لمفردات اليوم.'], [['Study the presented words and examples.', 'Return regularly and reuse the vocabulary in speaking or writing.'], ['ادرس الكلمات والأمثلة المعروضة.', 'عد بانتظام وأعد استخدام المفردات في التحدث أو الكتابة.']], ['STUDENT; own learning activity.', 'للطالب؛ نشاطه التعليمي.'], ['Content is platform-provided; any scheduled delivery is configuration-dependent.', 'المحتوى من المنصة؛ وأي جدولة للتسليم تعتمد على الإعداد.'], ['Supports vocabulary goals and conversation or writing practice.', 'يدعم أهداف المفردات وممارسة المحادثة أو الكتابة.']),
  make('student-vocabulary-flashcards', 'student', ['Vocabulary flashcards', 'بطاقات المفردات'], '/dashboard/student/vocabulary/flashcards', ['Practice recall with vocabulary cards.', 'التدرب على استدعاء المفردات باستخدام البطاقات.'], [['Review a prompt before revealing or checking the answer.', 'Repeat difficult terms and connect them to a real example.'], ['راجع السؤال قبل كشف الإجابة أو التحقق منها.', 'كرر المصطلحات الصعبة واربطها بمثال واقعي.']], ['STUDENT; personal practice.', 'للطالب؛ تدريب شخصي.'], ['Platform content and client interaction; no external service assumed.', 'محتوى المنصة وتفاعل الواجهة؛ لا يُفترض مزود خارجي.'], ['Reinforces words from learning material, lessons and feedback.', 'يعزز كلمات مواد التعلم والدروس والملاحظات.']),
  make('student-vocabulary-test', 'student', ['Vocabulary review', 'مراجعة المفردات'], '/dashboard/student/vocabulary/test', ['Check vocabulary recall in a practice context.', 'التحقق من استدعاء المفردات ضمن التدريب.'], [['Complete the available practice questions.', 'Use the result to guide study, not as a formal placement decision.'], ['أكمل أسئلة التدريب المتاحة.', 'استخدم النتيجة لتوجيه الدراسة لا قرار تحديد مستوى رسمي.']], ['STUDENT; self-practice only.', 'للطالب؛ تدريب ذاتي فقط.'], ['Platform activity; formal testing is not implied.', 'نشاط المنصة؛ لا يعني اختبارًا رسميًا.'], ['Provides a practice signal for vocabulary goals and review.', 'يوفر مؤشرًا تدريبيًا لأهداف المفردات والمراجعة.']),
  make('student-discover-words', 'student', ['Discover words', 'اكتشاف الكلمات'], '/dashboard/student/discover-words', ['Explore vocabulary and expressions beyond a single lesson.', 'استكشاف المفردات والتعبيرات خارج درس واحد.'], [['Search or browse the word material available.', 'Save useful terms through available platform actions.'], ['ابحث أو تصفح المواد المتاحة للكلمات.', 'احتفظ بالمصطلحات المفيدة عبر الإجراءات المتاحة.']], ['STUDENT; content availability depends on the platform catalogue.', 'للطالب؛ يعتمد توفر المحتوى على مكتبة المنصة.'], ['Internal learning content; external lookup is not assumed.', 'محتوى تعلم داخلي؛ لا يُفترض بحث خارجي.'], ['Extends vocabulary work connected to goals and feedback.', 'يوسع تعلم المفردات المرتبط بالأهداف والملاحظات.']),
  make('student-video-learning', 'student', ['Video learning', 'التعلم بالفيديو'], '/dashboard/student/video-learning', ['Study with video learning resources.', 'التعلم باستخدام موارد الفيديو.'], [['Choose a listed video resource.', 'Follow any level or skill guidance and return to record what was learned.'], ['اختر مورد فيديو من القائمة.', 'اتبع إرشادات المستوى أو المهارة وعد لتدوين ما تعلمته.']], ['STUDENT; published resource access rules apply.', 'للطالب؛ تنطبق قواعد الوصول للموارد المنشورة.'], ['Playback depends on the resource host, network and browser; no single video provider is guaranteed.', 'يعتمد التشغيل على مستضيف المورد والشبكة والمتصفح؛ لا يضمن مزود فيديو محدد.'], ['Resources support self-study between classes and goals.', 'تدعم الموارد الدراسة الذاتية بين الحصص والأهداف.']),
  make('student-conversation-practice', 'student', ['Conversation practice', 'ممارسة المحادثة'], '/dashboard/student/conversation-practice', ['Practice spoken English through available conversation activities.', 'ممارسة الإنجليزية المنطوقة عبر أنشطة المحادثة المتاحة.'], [['Choose a prompt or activity.', 'Practice speaking and note phrases to revisit with a teacher.'], ['اختر موضوعًا أو نشاطًا.', 'تدرب على التحدث وسجل العبارات لمراجعتها مع المدرس.']], ['STUDENT; practice content only.', 'للطالب؛ محتوى تدريب فقط.'], ['Microphone or speech features require browser permission and any configured speech provider.', 'تتطلب ميزات الميكروفون أو الكلام إذن المتصفح ومزودًا مضبوطًا إن وجد.'], ['Supports speaking goals and can prepare the learner for live classes.', 'يدعم أهداف التحدث ويهيئ المتعلم للحصص المباشرة.']),
  make('student-ai-assistant', 'student', ['Learning assistant', 'مساعد التعلم'], '/dashboard/student/ai-assistant', ['Provide an assisted learning experience where available.', 'تقديم تجربة تعلم مساعدة عند توفرها.'], [['Use the assistant for a learning question or practice.', 'Check generated advice and consult a teacher for assessment or personal guidance.'], ['استخدم المساعد لسؤال أو تدريب تعليمي.', 'تحقق من الاقتراحات واستشر المدرس للتقييم أو التوجيه الشخصي.']], ['STUDENT; use only information permitted for the learner account.', 'للطالب؛ استخدم المعلومات المسموح بها لحسابه فقط.'], ['AI provider availability is conditional. The master specification flags Thanarah readiness and exposed-key rotation as unresolved prerequisites.', 'توافر مزود الذكاء الاصطناعي مشروط. تشير المواصفة إلى ضرورة التحقق من Thanarah وتدوير المفتاح المكشوف.'], ['Can support practice; it does not replace teacher feedback or publish sensitive work automatically.', 'قد يدعم التدريب؛ ولا يحل محل ملاحظات المدرس أو ينشر عملًا حساسًا تلقائيًا.']),
  make('student-free-writing', 'student', ['Free writing', 'الكتابة الحرة'], '/dashboard/student/free-writing', ['Give the learner a space for independent writing practice.', 'توفير مساحة للمتعلم لممارسة الكتابة المستقلة.'], [['Write on a chosen topic or prompt.', 'Review and save using actions provided on the page.'], ['اكتب عن موضوع أو سؤال تختاره.', 'راجع واحفظ باستخدام الإجراءات المتاحة.']], ['STUDENT; own writing only.', 'للطالب؛ كتاباته فقط.'], ['Persistence and storage depend on the page’s configured platform data path.', 'يعتمد الحفظ والتخزين على مسار بيانات المنصة المضبوط للصفحة.'], ['Independent practice can be shared in class or used to inform learning goals.', 'يمكن مشاركة التدريب المستقل في الحصة أو استخدامه لتوجيه الأهداف.']),
  make('student-writings', 'student', ['My writings', 'كتاباتي'], '/dashboard/student/writings', ['Review the learner’s saved writing work.', 'مراجعة أعمال الكتابة المحفوظة للمتعلم.'], [['Open a writing entry to review it.', 'Use teacher feedback where available to revise the next piece.'], ['افتح نصًا لمراجعته.', 'استخدم ملاحظات المدرس عند توفرها لتحسين النص التالي.']], ['STUDENT; own writing only.', 'للطالب؛ كتاباته فقط.'], ['Uses platform writing records; file or rich-media storage is configuration-dependent.', 'يعتمد على سجلات الكتابة؛ وتخزين الملفات والوسائط الإضافية حسب الإعداد.'], ['Connects independent writing with teacher review and feedback.', 'يربط الكتابة المستقلة بمراجعة المدرس وملاحظاته.']),
  make('student-writing-tests', 'student', ['Writing practice', 'تدريب الكتابة'], '/dashboard/student/writing-tests', ['Offer structured writing practice or review.', 'تقديم تدريب كتابي منظم أو مراجعة.'], [['Read the prompt and complete the writing activity.', 'Treat results as practice unless a formal assessment is explicitly stated.'], ['اقرأ السؤال وأكمل النشاط الكتابي.', 'اعتبر النتائج تدريبًا ما لم يذكر التقييم الرسمي صراحة.']], ['STUDENT; own practice.', 'للطالب؛ تدريبه فقط.'], ['Platform activity; no external assessment system is implied.', 'نشاط المنصة؛ لا يُفترض نظام تقييم خارجي.'], ['Writing practice may become class discussion or teacher feedback.', 'قد يتحول التدريب الكتابي إلى نقاش في الحصة أو ملاحظات المدرس.']),
  make('student-test-words', 'student', ['Word practice', 'تدريب الكلمات'], '/dashboard/student/test-words', ['Practice recognition and recall of vocabulary.', 'التدرب على تمييز المفردات واستدعائها.'], [['Complete the available word activity.', 'Review missed words in vocabulary practice.'], ['أكمل نشاط الكلمات المتاح.', 'راجع الكلمات التي أخطأت فيها ضمن تدريب المفردات.']], ['STUDENT; practice data is learner-scoped.', 'للطالب؛ بيانات التدريب مرتبطة بالمتعلم.'], ['Internal practice feature; not a placement test.', 'ميزة تدريب داخلية؛ وليست اختبار تحديد مستوى.'], ['Reinforces vocabulary study and progress reflection.', 'تعزز دراسة المفردات والتأمل في التقدم.']),

  make('teacher-dashboard', 'teacher', ['Teacher dashboard', 'لوحة المدرس'], '/dashboard/teacher', ['Prioritize today’s classes, assigned learners and pending follow-up.', 'ترتيب أولويات حصص اليوم والطلاب المعيّنين والمتابعة المطلوبة.'], [['Review upcoming classes and learner follow-ups.', 'Open a class or learner only within your assignments.'], ['راجع الحصص القادمة ومتابعة المتعلمين.', 'افتح الحصة أو الطالب ضمن تعييناتك فقط.']], ['TEACHER; scope is assigned learners and classes.', 'للمدرس؛ ضمن الطلاب والحصص المعيّنة.'], ['Platform class records; live meeting access requires configured QMeet.', 'سجلات الحصص داخل المنصة؛ الاجتماع المباشر يتطلب QMeet مضبوطًا.'], ['Class activity flows to attendance, feedback, homework and learner progress.', 'ينتقل نشاط الحصة إلى الحضور والملاحظات والواجب وتقدم المتعلم.']),
  make('teacher-classes', 'teacher', ['My classes', 'حصصي'], '/dashboard/teacher/classes', ['Manage teaching sessions assigned to the teacher.', 'إدارة الجلسات التعليمية المعيّنة للمدرس.'], [['Check class roster, schedule and status.', 'Start the meeting or record session details when actions are available.'], ['تحقق من قائمة الطلاب والموعد والحالة.', 'ابدأ الاجتماع أو سجل تفاصيل الجلسة عند توفر الإجراء.']], ['TEACHER; only assigned classes and their learners.', 'للمدرس؛ حصصه وطلابها المعيّنون فقط.'], ['QMeet is the intended meeting integration, but API and embed readiness must be verified; Google Meet is not an assumed replacement.', 'QMeet هو التكامل المستهدف، لكن يجب التحقق من API والتضمين؛ ولا يُفترض Google Meet بديلًا.'], ['Scheduled → session/attendance → feedback pending → published feedback and homework.', 'مجدولة ← جلسة وحضور ← ملاحظات معلقة ← ملاحظات منشورة وواجب.']),
  make('teacher-classes-qmeet', 'teacher', ['QMeet class view', 'عرض حصة QMeet'], '/dashboard/teacher/classes?view=QMeet', ['Open the QMeet-oriented class view when available.', 'فتح عرض الحصص المرتبط بـQMeet عند توفره.'], [['Select QMeet from the class navigation.', 'Confirm the meeting state before inviting learners.'], ['اختر QMeet من تنقل الحصص.', 'تحقق من حالة الاجتماع قبل دعوة المتعلمين.']], ['TEACHER; meeting access is limited to assigned sessions.', 'للمدرس؛ الوصول للاجتماع ضمن الجلسات المعيّنة.'], ['Documented target API: POST/GET /api/qmeet/v1/meetings, GET /api/qmeet/v1/meetings/{roomName}, DELETE /api/qmeet/v1/meetings/{roomName}. These endpoints do not prove a verified production connection; rotate exposed credentials before use.', 'واجهة API المستهدفة الموثقة: POST/GET /api/qmeet/v1/meetings وGET /api/qmeet/v1/meetings/{roomName} وDELETE /api/qmeet/v1/meetings/{roomName}. وجود المسارات لا يثبت اتصالًا إنتاجيًا متحققًا؛ دوّر بيانات الاعتماد المكشوفة قبل الاستخدام.'], ['Extends the assigned class session and provides context for attendance and follow-up.', 'يمتد من الحصة المعيّنة ويوفر سياق الحضور والمتابعة.']),
  make('teacher-students', 'teacher', ['My students', 'طلابي'], '/dashboard/teacher/students', ['Find and follow up with learners assigned to the teacher.', 'العثور على المتعلمين المعيّنين للمدرس ومتابعتهم.'], [['Choose an assigned learner.', 'Review level, goals and recent learning activity before follow-up.'], ['اختر متعلمًا معيّنًا لك.', 'راجع المستوى والأهداف والنشاط الأخير قبل المتابعة.']], ['TEACHER; access to assigned learners only unless explicitly granted.', 'للمدرس؛ الطلاب المعيّنون فقط إلا بمنح صريح.'], ['Platform learner and class data; no external roster sync is assumed.', 'بيانات المتعلم والحصص داخل المنصة؛ لا يُفترض مزامنة قوائم خارجية.'], ['Learner context informs class preparation, feedback and homework.', 'يوجه سياق المتعلم تحضير الحصة والملاحظات والواجب.']),
  make('teacher-feedback', 'teacher', ['Feedback workspace', 'مساحة الملاحظات'], '/dashboard/teacher/feedback', ['Create, review and publish structured class feedback.', 'إنشاء ملاحظات الحصة المنظمة ومراجعتها ونشرها.'], [['Select an assigned class and learner.', 'Record strengths, EBI, vocabulary and private teacher notes separately.', 'Publish only after checking student-visible content.'], ['حدد حصة ومتعلماً ضمن تعييناتك.', 'سجل نقاط القوة وEBI والمفردات وافصل ملاحظات المدرس الخاصة.', 'لا تنشر قبل مراجعة المحتوى الظاهر للطالب.']], ['TEACHER; assigned class and learner access only.', 'للمدرس؛ الوصول للحصص والمتعلمين المعيّنين فقط.'], ['Platform feedback records; WhatsApp delivery requires a configured integration and learner consent.', 'سجلات الملاحظات داخل المنصة؛ يتطلب WhatsApp تكاملًا مضبوطًا وموافقة المتعلم.'], ['Class/session → draft → ready to publish → published feedback → student review and homework focus.', 'الحصة والجلسة ← مسودة ← جاهز للنشر ← ملاحظات منشورة ← مراجعة الطالب وتركيز الواجب.']),
  make('teacher-homework', 'teacher', ['Homework workspace', 'مساحة الواجبات'], '/dashboard/teacher/homework', ['Assign work and review student submissions.', 'تعيين العمل ومراجعة تسليمات الطلاب.'], [['Create work from an assigned class or learner context.', 'Set clear instructions, type and due date.', 'Review submissions and return feedback.'], ['أنشئ واجبًا من حصة أو سياق متعلم معيّن.', 'حدد التعليمات والنوع والموعد بوضوح.', 'راجع التسليمات وأعد الملاحظات.']], ['TEACHER; assigned learners and class work only.', 'للمدرس؛ الطلاب المعيّنون وأعمال حصصهم فقط.'], ['Uploads and media depend on configured durable storage; messaging notifications are conditional.', 'تعتمد الملفات والوسائط على تخزين دائم مضبوط؛ والإشعارات مشروطة.'], ['Feedback and class context → published homework → submission → review → completion and learner progress.', 'الملاحظات وسياق الحصة ← واجب منشور ← تسليم ← مراجعة ← إكمال وتقدم المتعلم.']),
  make('teacher-intelligence', 'teacher', ['Learning intelligence', 'ذكاء التعلّم'], '/dashboard/teacher/intelligence', ['Surface learner learning signals for teacher review.', 'عرض مؤشرات تعلم المتعلمين لمراجعة المدرس.'], [['Review signals for assigned learners.', 'Treat recommendations as prompts for professional review, not final assessment.'], ['راجع مؤشرات المتعلمين المعيّنين.', 'تعامل مع التوصيات كمقترحات للمراجعة لا كتقييم نهائي.']], ['TEACHER; assigned learner scope; sensitive learner data requires care.', 'للمدرس؛ ضمن نطاق المتعلمين المعيّنين مع حماية بياناتهم.'], ['AI/provider readiness is not presumed; Thanarah requires key rotation and real API contract verification per specification.', 'لا يُفترض جاهزية مزود الذكاء الاصطناعي؛ يتطلب Thanarah تدوير المفتاح والتحقق من عقد API الفعلي.'], ['May inform class preparation and practice proposals; teacher approval remains essential.', 'قد يوجه تحضير الحصة ومقترحات التدريب؛ وتبقى موافقة المدرس أساسية.']),
  make('teacher-speaking', 'teacher', ['Speaking', 'التحدث'], '/dashboard/teacher/speaking', ['Support speaking activities and teacher participation.', 'دعم أنشطة التحدث ومشاركة المدرس.'], [['Review available speaking spaces or activities.', 'Follow room and learner privacy rules.'], ['راجع مساحات أو أنشطة التحدث المتاحة.', 'اتبع قواعد الغرف وخصوصية المتعلمين.']], ['TEACHER; activity access follows role and assignment scope.', 'للمدرس؛ يخضع الوصول للدور ونطاق التعيين.'], ['Live rooms rely on the configured real-time service and are not assumed to be QMeet.', 'تعتمد الغرف المباشرة على خدمة آنية مضبوطة ولا يُفترض أنها QMeet.'], ['Supports speaking goals alongside assigned classes and student practice.', 'يدعم أهداف التحدث إلى جانب الحصص وممارسة الطالب.']),
  make('teacher-sessions', 'teacher', ['Teaching sessions', 'جلسات التدريس'], '/dashboard/teacher/sessions', ['Review teacher session records and follow-up context.', 'مراجعة سجلات جلسات المدرس وسياق المتابعة.'], [['Open a session assigned to you.', 'Check session notes and complete follow-up using the relevant feedback or homework area.'], ['افتح جلسة معيّنة لك.', 'راجع الملاحظات وأكمل المتابعة عبر مساحة الملاحظات أو الواجب.']], ['TEACHER; assigned sessions only.', 'للمدرس؛ الجلسات المعيّنة فقط.'], ['Session and attendance persistence is platform-dependent; live meeting provider remains QMeet-targeted.', 'يعتمد حفظ الجلسة والحضور على المنصة؛ ومزود الاجتماع المستهدف QMeet.'], ['Session record becomes context for feedback, homework and student progress.', 'يصبح سجل الجلسة سياقًا للملاحظات والواجب وتقدم الطالب.']),

  make('admin-overview', 'admin', ['Admin overview', 'نظرة الإدارة'], '/dashboard/admin', ['Monitor administration and reach core operational areas.', 'متابعة الإدارة والوصول إلى المساحات التشغيلية الأساسية.'], [['Use the overview to enter a tab or a dedicated route.', 'Verify underlying records before taking operational action.'], ['استخدم النظرة العامة لفتح تبويب أو مسار مستقل.', 'تحقق من السجلات قبل الإجراء التشغيلي.']], ['ADMIN only for this guide; dashboard layout also admits ASSISTANT and MANAGER, whose access is narrower and separately governed.', 'ADMIN فقط لهذا الدليل؛ تسمح حاوية اللوحة أيضًا بـASSISTANT وMANAGER بصلاحيات أضيق ومنفصلة.'], ['Platform APIs and integrations vary by module; a visible admin screen does not prove an integration is production-ready.', 'تختلف APIs والتكاملات حسب الوحدة؛ ظهور شاشة الإدارة لا يثبت جاهزية التكامل إنتاجيًا.'], ['Administrative oversight of learner, teacher, class, learning and system workflows.', 'إشراف إداري على مسارات المتعلم والمدرس والحصة والتعلم والنظام.']),
  make('admin-people', 'admin', ['People profiles', 'ملفات الأشخاص'], '/dashboard/admin/people', ['Review people records and operational context.', 'مراجعة سجلات الأشخاص وسياقهم التشغيلي.'], [['Search for the correct learner or team member.', 'Confirm identity and role scope before changing records.'], ['ابحث عن الطالب أو عضو الفريق الصحيح.', 'تحقق من الهوية ونطاق الدور قبل تغيير السجلات.']], ['ADMIN route; actual data actions follow backend role permissions.', 'مسار الإدارة؛ تخضع إجراءات البيانات لصلاحيات الخادم.'], ['Platform people records; external identity sync is not assumed.', 'سجلات الأشخاص داخل المنصة؛ لا يُفترض مزامنة خارجية.'], ['Central person context connects roles, classes, level, feedback and homework.', 'يربط سياق الشخص الأدوار والحصص والمستوى والملاحظات والواجب.']),
  make('admin-users', 'admin', ['Users tab', 'تبويب المستخدمين'], '/dashboard/admin?tab=users', ['Administer platform user accounts.', 'إدارة حسابات مستخدمي المنصة.'], [['Open a user record and verify role and account context.', 'Apply only permitted changes and check their effect on access.'], ['افتح سجل المستخدم وتحقق من الدور والسياق.', 'طبّق التغييرات المسموحة وتحقق من أثرها على الوصول.']], ['Admin tab; role changes and account actions must be server-authorized.', 'تبويب إدارة؛ يجب أن يصرح الخادم بتغيير الأدوار والحسابات.'], ['Platform account service; no external directory is assumed.', 'خدمة حسابات المنصة؛ لا يُفترض دليل مستخدمين خارجي.'], ['Controls entry into student, teacher and administration workflows.', 'يتحكم بالدخول لمسارات الطالب والمدرس والإدارة.']),
  make('admin-students', 'admin', ['Students tab', 'تبويب الطلاب'], '/dashboard/admin?tab=students', ['Manage student records in the legacy admin dashboard.', 'إدارة سجلات الطلاب في لوحة الإدارة الحالية.'], [['Find a learner and review their profile context.', 'Keep level, goals and assigned teacher aligned with current learning needs.'], ['اعثر على المتعلم وراجع سياق ملفه.', 'حافظ على توافق المستوى والأهداف والمدرس مع احتياجات التعلم.']], ['Admin tab; student data actions are subject to backend authorization and audit requirements.', 'تبويب إدارة؛ تخضع إجراءات بيانات الطالب لتصريح الخادم والتدقيق.'], ['Platform learner records; imported data requires verified provenance.', 'سجلات المتعلم داخل المنصة؛ تتطلب البيانات المستوردة مصدرًا موثقًا.'], ['Anchors student level/goals and their classes, feedback, homework and progress.', 'يربط مستوى الطالب وأهدافه بحصصه وملاحظاته وواجباته وتقدمه.']),
  make('admin-levels', 'admin', ['Levels', 'المستويات'], '/dashboard/admin/levels', ['Maintain learner levels and related progression context.', 'إدارة مستويات المتعلمين وسياق التقدم المرتبط.'], [['Review CEFR level and any configured sublevel.', 'Use explicit learning evidence when updating a learner level.'], ['راجع مستوى CEFR والمرحلة الفرعية المضبوطة.', 'استخدم أدلة تعلم واضحة عند تحديث المستوى.']], ['Admin route; changes affect learning eligibility and require appropriate authorization.', 'مسار إدارة؛ تؤثر التغييرات على ملاءمة التعلم وتتطلب تصريحًا مناسبًا.'], ['Platform level records; specification calls for CEFR A1–C2 and configurable sublevels.', 'سجلات المستوى بالمنصة؛ توصي المواصفة بـCEFR من A1 إلى C2 ومراحل فرعية قابلة للتهيئة.'], ['Level shapes resource visibility, learning goals and progress interpretation.', 'يحدد المستوى ظهور الموارد والأهداف وتفسير التقدم.']),
  make('admin-classes', 'admin', ['Classes', 'الحصص'], '/dashboard/admin/classes', ['Oversee class scheduling and operational context.', 'الإشراف على جدولة الحصص وسياقها التشغيلي.'], [['Review teacher, learner, time and session status.', 'Resolve assignment or schedule issues before the session.'], ['راجع المدرس والمتعلم والوقت وحالة الجلسة.', 'عالج مشكلات التعيين أو الجدولة قبل الجلسة.']], ['ADMIN route; changes should respect assignment and audit controls.', 'مسار إدارة؛ يجب احترام ضوابط التعيين والتدقيق.'], ['Calendar integrations are not guaranteed; QMeet readiness is separate from class records.', 'تكامل التقويم غير مضمون؛ وجاهزية QMeet منفصلة عن سجلات الحصص.'], ['Scheduled class → teacher session → attendance → feedback → homework.', 'حصة مجدولة ← جلسة المدرس ← الحضور ← الملاحظات ← الواجب.']),
  make('admin-feedback', 'admin', ['Feedback', 'التغذية الراجعة'], '/dashboard/admin/feedback', ['Oversee feedback records and publication flow.', 'الإشراف على سجلات الملاحظات ومسار النشر.'], [['Review class and learner linkage.', 'Protect private teacher notes and verify published student-visible content.'], ['راجع ارتباط الحصة والمتعلم.', 'احم ملاحظات المدرس الخاصة وتحقق من المحتوى الظاهر للطالب.']], ['ADMIN route; access to private teacher notes is sensitive and must follow authorization.', 'مسار إدارة؛ الوصول للملاحظات الخاصة حساس ويجب أن يخضع للتصريح.'], ['In-app feedback persistence; WhatsApp is optional and requires consent/configuration.', 'حفظ الملاحظات داخل المنصة؛ WhatsApp اختياري ويتطلب الموافقة والإعداد.'], ['After class, feedback bridges teacher observation to learner goals and homework.', 'بعد الحصة تربط الملاحظات رؤية المدرس بأهداف المتعلم وواجبه.']),
  make('admin-homework', 'admin', ['Homework', 'الواجبات'], '/dashboard/admin/homework', ['Oversee published assignments and their learner workflow.', 'الإشراف على الواجبات المنشورة ومسار المتعلم.'], [['Review assignment status, due date and class/learner links.', 'Check submission and review stages when resolving issues.'], ['راجع حالة الواجب والموعد وارتباط الحصة أو المتعلم.', 'تحقق من مراحل التسليم والمراجعة عند حل المشكلات.']], ['ADMIN route; learner submissions and files are sensitive.', 'مسار إدارة؛ تسليمات المتعلم وملفاته حساسة.'], ['File storage and notifications depend on production configuration.', 'يعتمد تخزين الملفات والإشعارات على إعداد الإنتاج.'], ['DRAFT → PUBLISHED → OPEN → SUBMITTED → REVIEWED → COMPLETED.', 'مسودة ← منشور ← مفتوح ← تم التسليم ← تمت المراجعة ← مكتمل.']),
  make('admin-lessons', 'admin', ['Lessons tab', 'تبويب الدروس'], '/dashboard/admin?tab=lessons', ['Manage lesson content in the legacy dashboard tab.', 'إدارة محتوى الدروس في تبويب لوحة الإدارة الحالية.'], [['Review lesson title, level, skill and publication status.', 'Ensure material is suitable for the learner’s level before publishing.'], ['راجع عنوان الدرس ومستواه ومهارته وحالة نشره.', 'تأكد من ملاءمة المادة للمستوى قبل النشر.']], ['Admin tab; publication affects student-visible learning materials.', 'تبويب إدارة؛ يؤثر النشر على مواد التعلم الظاهرة للطالب.'], ['Media hosting depends on configured storage or the linked content provider.', 'تعتمد استضافة الوسائط على التخزين المضبوط أو مزود المحتوى المرتبط.'], ['Published lessons connect admin content to student learning and progress.', 'تربط الدروس المنشورة محتوى الإدارة بتعلم الطالب وتقدمه.']),
  make('admin-placement-test', 'admin', ['Placement test tab', 'تبويب اختبار تحديد المستوى'], '/dashboard/admin?tab=placement-test', ['Access legacy placement-test tooling where present.', 'الوصول لأدوات تحديد المستوى الحالية عند توفرها.'], [['Review current availability and its intended use.', 'Do not treat test output as authoritative until assessment policy and validation are confirmed.'], ['راجع التوفر الحالي والغرض من الأداة.', 'لا تعتمد النتيجة نهائيًا قبل تأكيد سياسة التقييم والتحقق.']], ['Admin tab; placement decisions require authorized review.', 'تبويب إدارة؛ قرارات المستوى تحتاج مراجعة مخولة.'], ['Test validity and any external assessment provider are not established by the route alone.', 'لا يثبت المسار صلاحية الاختبار أو وجود مزود تقييم خارجي.'], ['May inform level assignment; specification says initial level is teacher/admin-set and tests are not MVP.', 'قد يساعد في تعيين المستوى؛ وتنص المواصفة أن المستوى الأولي يحدده المدرس أو الإدارة وأن الاختبارات ليست ضمن MVP.']),
  make('admin-page-editor', 'admin', ['Page editor tab', 'تبويب محرر الصفحات'], '/dashboard/admin?tab=page-editor', ['Edit public-facing page content through the existing admin tool.', 'تحرير محتوى الصفحات العامة عبر أداة الإدارة الحالية.'], [['Review the target page and its current content.', 'Preview changes before publishing them to visitors.'], ['راجع الصفحة المستهدفة ومحتواها الحالي.', 'عاين التغييرات قبل نشرها للزوار.']], ['Admin tab; public content changes should be reviewed before publication.', 'تبويب إدارة؛ يجب مراجعة تغييرات المحتوى العام قبل النشر.'], ['Uses platform content storage; external CMS synchronization is not assumed.', 'يستخدم تخزين محتوى المنصة؛ لا يُفترض تزامن CMS خارجي.'], ['Changes public discovery and can route visitors into registration or sign-in.', 'تؤثر التغييرات على اكتشاف المنصة وتوجيه الزائر للتسجيل أو الدخول.']),
  make('admin-leads', 'admin', ['Booking requests tab', 'تبويب طلبات الحجز'], '/dashboard/admin?tab=leads', ['Review incoming booking or contact requests.', 'مراجعة طلبات الحجز أو التواصل الواردة.'], [['Review request details and follow the team’s contact process.', 'Record outcomes in the permitted workflow; avoid duplicating learner accounts.'], ['راجع تفاصيل الطلب واتبع إجراء التواصل المعتمد.', 'سجل النتيجة في المسار المسموح وتجنب تكرار حسابات المتعلمين.']], ['Admin tab; contact details are personal data.', 'تبويب إدارة؛ بيانات الاتصال معلومات شخصية.'], ['Outbound email or WhatsApp follow-up depends on configured integrations and consent.', 'يعتمد التواصل عبر البريد أو WhatsApp على التكامل والموافقة.'], ['Can lead to an account, level/goals onboarding and class assignment.', 'قد يؤدي إلى حساب وتهيئة المستوى والأهداف وتعيين حصة.']),
  make('admin-subscriptions', 'admin', ['Subscription payments tab', 'تبويب دفعات الاشتراك'], '/dashboard/admin?tab=subscriptions', ['Review subscription payment records requiring administrative attention.', 'مراجعة سجلات دفعات الاشتراك التي تتطلب متابعة إدارية.'], [['Compare payment status with the related account or order.', 'Escalate discrepancies using the approved reconciliation process.'], ['قارن حالة الدفع بالحساب أو الطلب المرتبط.', 'صعّد الفروقات عبر إجراء التسوية المعتمد.']], ['Admin tab; financial operations should be restricted and audited.', 'تبويب إدارة؛ يجب تقييد العمليات المالية وتدقيقها.'], ['Payment gateway reconciliation is provider-dependent and not asserted as active.', 'تعتمد تسوية بوابة الدفع على المزود ولا يُؤكد أنها مفعلة.'], ['Payment status may influence access to packages and learning groups.', 'قد تؤثر حالة الدفع على الوصول للباقات ومجموعات التعلم.']),
  make('admin-coupons', 'admin', ['Coupons tab', 'تبويب الكوبونات'], '/dashboard/admin?tab=coupons', ['Manage promotional coupon records in the legacy admin area.', 'إدارة سجلات القسائم الترويجية في لوحة الإدارة الحالية.'], [['Review code, validity and intended offer.', 'Confirm checkout behavior after any configuration change.'], ['راجع الرمز والصلاحية والعرض المقصود.', 'تحقق من سلوك الدفع بعد أي تغيير بالإعداد.']], ['Admin tab; financial promotions require authorized changes.', 'تبويب إدارة؛ العروض المالية تتطلب تغييرات مخولة.'], ['Coupon redemption depends on the checkout and payment configuration.', 'يعتمد استخدام القسائم على إعداد الدفع وإتمام الشراء.'], ['Affects package purchase and checkout totals.', 'يؤثر على شراء الباقات وإجمالي الدفع.']),
  make('admin-email', 'admin', ['Direct email tab', 'تبويب البريد المباشر'], '/dashboard/admin?tab=email', ['Support authorized direct email operations.', 'دعم عمليات البريد المباشر المصرح بها.'], [['Verify recipient and message purpose before sending.', 'Use only approved templates and consent-based contact rules.'], ['تحقق من المستلم وغرض الرسالة قبل الإرسال.', 'استخدم القوالب المعتمدة وقواعد التواصل المبنية على الموافقة.']], ['Admin tab; sending should be limited to authorized staff.', 'تبويب إدارة؛ الإرسال يقتصر على الفريق المخول.'], ['Email provider and delivery status require configured mail credentials and service.', 'يتطلب مزود البريد وحالة التسليم بيانات اعتماد وخدمة مضبوطة.'], ['May inform users about their account or learning workflow; does not replace in-app records.', 'قد يبلغ المستخدمين بشأن الحساب أو التعلم؛ ولا يحل محل سجلات المنصة.']),
  make('admin-system', 'admin', ['System logs and settings tab', 'تبويب سجلات النظام والإعدادات'], '/dashboard/admin?tab=system', ['Inspect available operational diagnostics and system settings.', 'فحص التشخيصات التشغيلية والإعدادات المتاحة.'], [['Use logs to investigate, not expose secrets or personal content.', 'Change configuration only through approved secret and deployment processes.'], ['استخدم السجلات للتحقق دون كشف الأسرار أو المحتوى الشخصي.', 'غيّر الإعدادات عبر إجراءات الأسرار والنشر المعتمدة فقط.']], ['Admin tab; sensitive system settings require least privilege and audit.', 'تبويب إدارة؛ إعدادات النظام الحساسة تتطلب أقل صلاحية وتدقيقًا.'], ['Integrations fail clearly when secrets or persistent services are missing; secrets belong in a secret manager.', 'يجب أن تفشل التكاملات بوضوح عند غياب الأسرار أو الخدمات الدائمة؛ وتحفظ الأسرار في مدير أسرار.'], ['Operational health underpins learning, communication, meeting and storage flows.', 'تدعم سلامة التشغيل مسارات التعلم والتواصل والاجتماعات والتخزين.']),
  make('admin-commerce', 'admin', ['Packages and groups', 'الباقات والمجموعات'], '/dashboard/admin/commerce', ['Oversee commercial packages and learning group operations.', 'الإشراف على الباقات والعمليات التجارية للمجموعات.'], [['Review package, enrollment and group context.', 'Verify access consequences before changing a commercial record.'], ['راجع سياق الباقة والتسجيل والمجموعة.', 'تحقق من أثر الوصول قبل تعديل سجل تجاري.']], ['ADMIN route; commerce and enrollment changes are sensitive.', 'مسار إدارة؛ تغييرات التجارة والتسجيل حساسة.'], ['Payment completion is gateway-dependent; enrollment records are platform-managed.', 'يعتمد إتمام الدفع على بوابة الدفع؛ وتدار سجلات التسجيل داخل المنصة.'], ['Connects purchase and enrollment to group/class allocation and learner access.', 'يربط الشراء والتسجيل بتوزيع المجموعات والحصص ووصول المتعلم.']),
  make('admin-speaking', 'admin', ['Speaking rooms', 'غرف المحادثة'], '/dashboard/admin/speaking', ['Oversee speaking-room availability and related operations.', 'الإشراف على توفر غرف المحادثة والعمليات المرتبطة.'], [['Review room setup and participation context.', 'Check the active provider and privacy rules before enabling a room.'], ['راجع إعداد الغرفة وسياق المشاركة.', 'تحقق من المزود الفعال وقواعد الخصوصية قبل تفعيل الغرفة.']], ['ADMIN route; participation records and learner information are sensitive.', 'مسار إدارة؛ سجلات المشاركة وبيانات المتعلم حساسة.'], ['Real-time provider and persistent process availability are deployment-dependent.', 'يعتمد مزود الوقت الحقيقي والخدمات الدائمة على النشر.'], ['Complements assigned classes and student speaking practice.', 'يكمل الحصص المعيّنة وتدريب الطالب على المحادثة.']),
  make('admin-intelligence', 'admin', ['Learning intelligence', 'ذكاء التعلّم'], '/dashboard/admin/intelligence', ['Review learning signals across authorized administrative scope.', 'مراجعة مؤشرات التعلم ضمن النطاق الإداري المصرح.'], [['Review data provenance and learner scope.', 'Treat recommendations as review aids and never as unapproved automated decisions.'], ['راجع مصدر البيانات ونطاق المتعلم.', 'تعامل مع التوصيات كوسائل مساعدة لا كقرارات آلية غير معتمدة.']], ['ADMIN route; broad student data requires careful access controls.', 'مسار إدارة؛ تتطلب بيانات الطلاب الواسعة ضوابط وصول دقيقة.'], ['AI outputs require configured provider, privacy review and verified API contract; Thanarah readiness is flagged unresolved.', 'تتطلب مخرجات الذكاء الاصطناعي مزودًا مضبوطًا ومراجعة خصوصية وعقد API متحققًا؛ وجاهزية Thanarah غير محسومة.'], ['Signals may connect goals, feedback, homework and progress; human review stays in the loop.', 'قد تربط المؤشرات الأهداف والملاحظات والواجب والتقدم؛ وتبقى المراجعة البشرية أساسية.']),
  make('admin-whatsapp', 'admin', ['WhatsApp CRM', 'إدارة WhatsApp'], '/dashboard/admin/whatsapp', ['Manage authorized WhatsApp CRM conversations and connection state.', 'إدارة حالة اتصال WhatsApp ومحادثات CRM المصرح بها.'], [['Check connection status before relying on messages.', 'Respect contact identity and consent; distinguish human replies from automated notifications.'], ['تحقق من حالة الاتصال قبل الاعتماد على الرسائل.', 'احترم هوية جهة الاتصال والموافقة وميّز الرد اليدوي عن الإشعارات الآلية.']], ['ADMIN or explicitly permitted roles; CRM conversation data is sensitive.', 'لـADMIN أو الأدوار الممنوحة صراحة؛ بيانات المحادثات حساسة.'], ['Linked-device QR is for WhatsApp connection only, not authentication. Requires a durable worker/session store; official OTP delivery is not provided by Baileys.', 'QR ربط الجهاز مخصص لاتصال WhatsApp لا للمصادقة. يحتاج عاملًا دائمًا وتخزين جلسة؛ ولا يوفر Baileys رموز OTP رسمية.'], ['Can notify learners about published feedback or homework only when configured and consented; queued delivery and audit are expected.', 'قد يخطر المتعلمين بالملاحظات المنشورة أو الواجب عند الإعداد والموافقة؛ ويتوقع الإرسال عبر Queue والتدقيق.']),
  make('manager-workspace', 'admin', ['Manager workspace', 'مساحة المدير'], '/dashboard/manager', ['Give MANAGER a scoped operational workspace.', 'توفير مساحة تشغيلية بنطاق صلاحية المدير.'], [['Use only the routes enabled for the manager role.', 'Request ADMIN support for actions outside assigned manager permissions.'], ['استخدم المسارات المتاحة لدور MANAGER فقط.', 'اطلب دعم ADMIN للإجراءات خارج صلاحيات المدير.']], ['MANAGER is not ADMIN. Do not use this guide or its admin-only entry to widen manager access.', 'MANAGER ليس ADMIN. لا تستخدم هذا الدليل أو مدخله الإداري لتوسيع صلاحيات المدير.'], ['Access derives from ROLE_PERMISSIONS and specific grants; WhatsApp and learning intelligence remain distinct permissions.', 'يستند الوصول إلى ROLE_PERMISSIONS والمنح المحددة؛ وتبقى WhatsApp وذكاء التعلم صلاحيات مميزة.'], ['Scoped operations can include assigned classes, people, levels and commerce according to explicit grants.', 'قد تشمل العمليات ذات النطاق الحصص والأشخاص والمستويات والتجارة بحسب المنح الصريحة.']),
]

export const GUIDE_GROUPS: GuideGroup[] = ['public', 'student', 'teacher', 'admin']

export function getScreenshotPath(slug: string, availableSlugs: ReadonlySet<string>) {
  return availableSlugs.has(slug) ? `/tips/screens/${slug}.png` : null
}

export function canAccessTips(role: string) {
  return role === 'ADMIN'
}

export function validateRegistry(entries: readonly GuideEntry[] = TIPS_REGISTRY): string[] {
  const errors: string[] = []
  const seen = new Set<string>()
  for (const entry of entries) {
    if (!entry.slug || seen.has(entry.slug)) errors.push(`Duplicate or empty screenshot slug: ${entry.slug}`)
    seen.add(entry.slug)
    if (!entry.route.startsWith('/')) errors.push(`Route must be absolute: ${entry.slug}`)
    if (!entry.title.en || !entry.title.ar || !entry.purpose.en || !entry.purpose.ar) {
      errors.push(`Missing bilingual title or purpose: ${entry.slug}`)
    }
    if (!entry.instructions.en.length || !entry.instructions.ar.length) {
      errors.push(`Missing bilingual instructions: ${entry.slug}`)
    }
  }
  return errors
}