// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/befluent-footer/CurrentHomeFooter.tsx": () => import("../components/mockups/befluent-footer/CurrentHomeFooter.tsx"),
  "./components/mockups/befluent-footer/SharedMarketingFooter.tsx": () => import("../components/mockups/befluent-footer/SharedMarketingFooter.tsx"),
  "./components/mockups/bfluent-admin-assistant/Current.tsx": () => import("../components/mockups/bfluent-admin-assistant/Current.tsx"),
  "./components/mockups/bfluent-current/CurrentAdmin.tsx": () => import("../components/mockups/bfluent-current/CurrentAdmin.tsx"),
  "./components/mockups/bfluent-current/CurrentStudent.tsx": () => import("../components/mockups/bfluent-current/CurrentStudent.tsx"),
  "./components/mockups/bfluent-current/CurrentTeacherFeedback.tsx": () => import("../components/mockups/bfluent-current/CurrentTeacherFeedback.tsx"),
  "./components/mockups/bfluent-current/primitives.tsx": () => import("../components/mockups/bfluent-current/primitives.tsx"),
  "./components/mockups/bfluent-redesign/AdminOverview.tsx": () => import("../components/mockups/bfluent-redesign/AdminOverview.tsx"),
  "./components/mockups/bfluent-redesign/StudentHome.tsx": () => import("../components/mockups/bfluent-redesign/StudentHome.tsx"),
  "./components/mockups/bfluent-redesign/TeacherFeedback.tsx": () => import("../components/mockups/bfluent-redesign/TeacherFeedback.tsx"),
  "./components/mockups/bfluent-teacher-workspace/Current.tsx": () => import("../components/mockups/bfluent-teacher-workspace/Current.tsx")
};
